- title: Menu
  items:
    - route: admin.dashboard.index
      title: Dashboard
      icon: nav-dashboard
    - route: admin.accounts.index
      permission: admin.accounts.view
      title: Accounts
      icon: nav-accounts
    - route: admin.tenants.index
      permission: admin.tenants.view
      title: Tenants
      icon: nav-tenants

- title: System
  items:
    - route: admin.system.database
      permission: admin.system.database.view
      title: Database
      icon: nav-database
    - route: admin.system.changelog.index
      permission: admin.system.changelog.view
      title: Changelog
      icon: nav-changelog
    - route: admin.system.server
      permission: admin.system.server.view
      title: Server
      icon: nav-server
    - route: admin.system.open-source
      title: Open source
      icon: nav-opensource
    - route: admin.system.styleguide
      title: Styleguide
      icon: nav-styleguide
      permission: admin.system.styleguide.view
